# Generated by Django 5.2.9 on 2025-12-09 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_visit_payer_type_visit_room_alter_visit_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateTimeField(auto_now_add=True)),
                ('body_region', models.CharField(choices=[('chest', 'Chest'), ('abdomen', 'Abdomen'), ('spine_cervical', 'Cervical Spine'), ('spine_thoracic', 'Thoracic Spine'), ('spine_lumbar', 'Lumbar Spine'), ('skull', 'Skull'), ('shoulder', 'Shoulder'), ('elbow', 'Elbow'), ('wrist', 'Wrist/Hand'), ('hip', 'Hip/Pelvis'), ('knee', 'Knee'), ('ankle', 'Ankle/Foot'), ('other', 'Other')], max_length=20)),
                ('view_type', models.CharField(choices=[('pa', 'PA (Posterior-Anterior)'), ('ap', 'AP (Anterior-Posterior)'), ('lateral', 'Lateral'), ('oblique', 'Oblique'), ('lordotic', 'Lordotic'), ('decubitus', 'Decubitus'), ('multiple', 'Multiple Views')], default='ap', max_length=20)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('bilateral', 'Bilateral'), ('na', 'Not Applicable')], default='na', max_length=15)),
                ('clinical_indication', models.TextField(help_text='Clinical question or reason for X-ray')),
                ('clinical_history', models.TextField(blank=True, help_text='Relevant patient history')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('ai_analyzed', 'AI Analyzed'), ('reported', 'Reported'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_studies', to='patients.patient')),
                ('radiographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_xrays', to=settings.AUTH_USER_MODEL)),
                ('reporting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_xrays', to=settings.AUTH_USER_MODEL)),
                ('requesting_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_xrays', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_studies', to='patients.visit')),
            ],
            options={
                'verbose_name': 'X-ray Study',
                'verbose_name_plural': 'X-ray Studies',
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='XrayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.TextField(blank=True, help_text='Imaging technique used')),
                ('findings', models.TextField(help_text='Detailed radiological findings')),
                ('impression', models.TextField(help_text='Summary impression/diagnosis')),
                ('recommendations', models.TextField(blank=True, help_text='Follow-up recommendations')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_xray_reports', to=settings.AUTH_USER_MODEL)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='xray.xraystudy')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='XrayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xray_images/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='xray.xraystudy')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='XrayDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='xray_documents/%Y/%m/')),
                ('doc_type', models.CharField(choices=[('referral', 'Referral Letter'), ('previous_report', 'Previous Report'), ('clinical_notes', 'Clinical Notes'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='xray.xraystudy')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='XrayAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_summary', models.TextField(blank=True)),
                ('technical_assessment', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('confidence_level', models.CharField(blank=True, max_length=20)),
                ('raw_response', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='xray.xraystudy')),
            ],
            options={
                'verbose_name': 'X-ray AI Analysis',
                'verbose_name_plural': 'X-ray AI Analyses',
            },
        ),
    ]
