# Generated by Django 5.2.9 on 2025-12-07 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TINValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(db_index=True, max_length=50)),
                ('id_type', models.CharField(default='BRN', help_text='ID Type (BRN, NRIC, etc.)', max_length=20)),
                ('id_value', models.CharField(blank=True, max_length=50)),
                ('is_valid', models.BooleanField(default=False)),
                ('taxpayer_name', models.CharField(blank=True, max_length=200)),
                ('validation_response', models.JSONField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TIN Validation',
                'verbose_name_plural': 'TIN Validations',
                'ordering': ['-validated_at'],
            },
        ),
        migrations.CreateModel(
            name='EInvoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, help_text='MyInvois Client ID', max_length=200)),
                ('client_secret', models.CharField(blank=True, help_text='MyInvois Client Secret (encrypted)', max_length=200)),
                ('taxpayer_tin', models.CharField(blank=True, help_text="Clinic's Tax Identification Number", max_length=50)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Enable e-invoicing')),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('clinic_brn', models.CharField(blank=True, help_text='Business Registration Number', max_length=50)),
                ('clinic_address_line1', models.CharField(blank=True, max_length=200)),
                ('clinic_address_line2', models.CharField(blank=True, max_length=200)),
                ('clinic_city', models.CharField(blank=True, max_length=100)),
                ('clinic_state', models.CharField(blank=True, max_length=100)),
                ('clinic_postcode', models.CharField(blank=True, max_length=20)),
                ('clinic_country', models.CharField(default='MYS', max_length=5)),
                ('clinic_phone', models.CharField(blank=True, max_length=20)),
                ('clinic_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Invoice Configuration',
                'verbose_name_plural': 'E-Invoice Configuration',
            },
        ),
        migrations.CreateModel(
            name='EInvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('refund_note', 'Refund Note')], default='invoice', max_length=20)),
                ('myinvois_uuid', models.CharField(blank=True, db_index=True, help_text='UUID returned by MyInvois', max_length=100)),
                ('submission_uid', models.CharField(blank=True, help_text='Submission ID from MyInvois', max_length=100)),
                ('long_id', models.CharField(blank=True, help_text='Long ID for document retrieval', max_length=200)),
                ('internal_id', models.CharField(help_text='Internal document reference', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('environment', models.CharField(default='sandbox', max_length=20)),
                ('payload_json', models.JSONField(blank=True, help_text='The JSON payload sent to MyInvois', null=True)),
                ('response_json', models.JSONField(blank=True, help_text='Response from MyInvois', null=True)),
                ('validation_errors', models.JSONField(blank=True, help_text='Validation errors if rejected', null=True)),
                ('buyer_tin', models.CharField(blank=True, help_text="Buyer's TIN", max_length=50)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='einvoice_documents', to='finance.invoice')),
                ('panel_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='einvoice_documents', to='finance.panelclaim')),
            ],
            options={
                'verbose_name': 'E-Invoice Document',
                'verbose_name_plural': 'E-Invoice Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EInvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('get_status', 'Get Status'), ('cancel', 'Cancel'), ('reject', 'Reject'), ('validate_tin', 'Validate TIN'), ('authenticate', 'Authenticate')], max_length=20)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='einvoice.einvoicedocument')),
            ],
            options={
                'verbose_name': 'E-Invoice Log',
                'verbose_name_plural': 'E-Invoice Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
