# Generated by Django 5.2.9 on 2025-12-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='brn',
            field=models.CharField(blank=True, help_text='Business Registration Number', max_length=50),
        ),
        migrations.AddField(
            model_name='panel',
            name='tin',
            field=models.CharField(blank=True, help_text='Tax Identification Number for e-invoicing', max_length=50),
        ),
    ]
