# Generated by Django 5.2.9 on 2025-12-07 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Master switch for AI features')),
                ('model_name', models.CharField(default='gpt-4o-mini', help_text='OpenAI model to use', max_length=50)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('temperature', models.DecimalField(decimal_places=1, default=0.7, max_digits=2)),
                ('triage_enabled', models.BooleanField(default=True)),
                ('consultation_notes_enabled', models.BooleanField(default=True)),
                ('medical_summary_enabled', models.BooleanField(default=True)),
                ('referral_letter_enabled', models.BooleanField(default=True)),
                ('stock_suggestion_enabled', models.BooleanField(default=True)),
                ('dashboard_insights_enabled', models.BooleanField(default=True)),
                ('revenue_forecast_enabled', models.BooleanField(default=True)),
                ('anomaly_detection_enabled', models.BooleanField(default=True)),
                ('assistant_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configuration',
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('triage', 'Triage Classification'), ('consultation_notes', 'Consultation Notes'), ('medical_summary', 'Medical History Summary'), ('referral_letter', 'Referral Letter'), ('quarantine_slip', 'Quarantine Slip'), ('stock_suggestion', 'Stock Order Suggestion'), ('dashboard_insight', 'Dashboard Insight'), ('revenue_forecast', 'Revenue Forecast'), ('anomaly_detection', 'Anomaly Detection'), ('assistant', 'AI Assistant'), ('nl_query', 'Natural Language Query'), ('lab_extraction', 'Lab Result Extraction')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limited')], default='success', max_length=20)),
                ('input_summary', models.TextField(help_text='Truncated/anonymized input for traceability')),
                ('output_summary', models.TextField(blank=True, help_text='Truncated output for traceability')),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Log',
                'verbose_name_plural': 'AI Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
