# Generated by Django 5.2.9 on 2025-12-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_type',
            field=models.CharField(choices=[('nric', 'NRIC'), ('passport', 'Passport')], default='nric', max_length=10),
        ),
    ]
