# Generated by Django 5.2.9 on 2025-12-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='mc_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mc_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mc_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mc_reason',
            field=models.CharField(blank=True, choices=[('unfit_work', 'Unfit for Work'), ('unfit_school', 'Unfit for School'), ('hospitalization', 'Hospitalization'), ('rest', 'Rest at Home'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
