# Generated by Django 5.2.9 on 2025-12-07 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_consultation_mc_days_consultation_mc_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='payer_type',
            field=models.CharField(choices=[('self_pay', 'Self Pay'), ('corporate', 'Corporate'), ('insurance', 'Insurance')], default='self_pay', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting_triage', 'Waiting - Triage'), ('waiting_doctor', 'Waiting - Doctor'), ('in_consultation', 'In Consultation'), ('to_pharmacy', 'To Pharmacy'), ('to_lab', 'To Lab'), ('ready_for_payment', 'Ready for Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting_triage', max_length=30),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('medical', 'Medical Visit'), ('otc', 'Over The Counter'), ('followup', 'Follow-up'), ('emergency', 'Emergency'), ('vaccination', 'Vaccination')], default='medical', max_length=20),
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_systolic', models.IntegerField(blank=True, null=True, verbose_name='BP Systolic')),
                ('bp_diastolic', models.IntegerField(blank=True, null=True, verbose_name='BP Diastolic')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Heart Rate (bpm)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)')),
                ('spo2', models.IntegerField(blank=True, null=True, verbose_name='SpO2 (%)')),
                ('pain_score', models.IntegerField(blank=True, null=True, verbose_name='Pain Score (0-10)')),
                ('notes', models.TextField(blank=True)),
                ('allergy_flag', models.BooleanField(default=False, verbose_name='Allergy Alert')),
                ('infection_risk', models.BooleanField(default=False, verbose_name='Infection Risk')),
                ('fall_risk', models.BooleanField(default=False, verbose_name='Fall Risk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='patients.visit')),
            ],
        ),
    ]
